spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_manage?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  freemarker:
    request-context-attribute: rca


mybatis:
  mapper-locations: classpath*:/**/*Mapper.xml




